-CREATE DATABASE library_database;

-- Create table 'branch'
DROP TABLE IF EXISTS BRANCH;
CREATE TABLE BRANCH
(
    BRANCH_ID VARCHAR(10) PRIMARY KEY,
    MANAGER_ID VARCHAR(10),
    BRANCH_ADDRESS VARCHAR(50),
    CONTACT_NO VARCHAR(20)
);

-- Create table 'employee'
DROP TABLE IF EXISTS EMPLOYEES;
CREATE TABLE EMPLOYEES
(
    EMP_ID VARCHAR(10) PRIMARY KEY,
    EMP_NAME VARCHAR(30),
    POSITION VARCHAR(20),
    SALARY INT,
    BRANCH_ID VARCHAR(10),
);

-- Create table 'members'
DROP TABLE IF EXISTS MEMBERS;
CREATE TABLE MEMBERS
(
    MEMBER_ID VARCHAR(10) PRIMARY KEY,
    MEMBER_NAME VARCHAR(25),
    MEMBER_ADDRESS VARCHAR(75),
    REG_DATE DATE
);

-- Create table 'books'
DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS
(
            ISBN VARCHAR(20) PRIMARY KEY,
            BOOK_TITLE VARCHAR(70),
            CATEGORY VARCHAR(25),
            RENTAL_PRICE FLOAT,
            STATUS VARCHAR(15),
            AUTHOR VARCHAR(25),
            PUBLISHER VARCHAR(25)
);

-- Create table 'issued_status'
DROP TABLE IF EXISTS ISSUED_STATUS;
CREATE TABLE ISSUED_STATUS
(
            ISSUED_ID VARCHAR(10) PRIMARY KEY,
            ISSUED_MEMBER_ID VARCHAR(10),
            ISSUED_BOOK_NAME VARCHAR(75),
            ISSUED_DATE DATE,
            ISSUED_BOOK_ISBN VARCHAR(25),
            ISSUED_EMP_ID VARCHAR(10)
);

-- Create table 'return_status'
DROP TABLE IF EXISTS RETURN_STATUS;
CREATE TABLE RETURN_STATUS
(
	RETURN_ID VARCHAR(10) PRIMARY KEY,
	ISSUED_ID VARCHAR(10),
	RETURN_BOOK_NAME VARCHAR(75),
	RETURN_DATE DATE,
	RETURN_BOOK_ISBN VARCHAR(25)
);

---for foreign keys

ALTER TABLE ISSUED_STATUS
ADD CONSTRAINT MEMBERS_FKEY
FOREIGN KEY ISSUED_MEMBER_ID
REFERENCES MEMBERS(MEMBER_ID)

ALTER TABLE ISSUED_STATUS
ADD CONSTRAINT BOOKS_FKEY
FOREIGN KEY ISSUED_BOOK_ISBN
REFERENCES BOOKS(ISBN)

ALTER TABLE ISSUED_STATUS---
ADD CONSTRAINT EMPLOYEES_FKEY
FOREIGN KEY ISSUED_EMP_ID
REFERENCES EMPLOYEES(EMP_ID)

ALTER TABLE EMPLOYEES
ADD CONSTRAINT BRANCH_FKEY
FOREIGN KEY BRANCH_ID
REFERENCES BRANCH(BRANCH_ID)

ALTER TABLE RETURN_STATUS
ADD CONSTRAINT ISSUED_STATUS_FKEY
FOREIGN KEY ISSUED_ID
REFERENCES ISSUED_STATUS(ISSUED_ID)

ALTER TABLE RETURN_STATUS
ADD CONSTRAINT BOOKS_FKEY
FOREIGN KEY ISBN
REFERENCES RETURN_STATUS(RETURN_BOOK_ISBN)
